import unittest


class T(unittest.TestCase):
    def test_raise(self):
        try:
            with self.assertRaises(ValueError):
                int('x')
        except Exception:
            with self.subTest():
                self.assertTrue(True)
